version: '3.5'

services:
  db:
    image: postgres:14.5-alpine
    container_name: postgres-efcore
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=efcore
    ports:
      - '5435:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local