CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220926230651_PrimeiraMigracao') THEN
    CREATE TABLE "Clientes" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Nome" VARCHAR(80) NOT NULL,
        "Telefone" CHAR(11) NULL,
        "CEP" CHAR(8) NOT NULL,
        "Estado" CHAR(2) NOT NULL,
        "Cidade" character varying(60) NOT NULL,
        CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220926230651_PrimeiraMigracao') THEN
    CREATE TABLE "Produtos" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "CodigoBarras" VARCHAR(14) NOT NULL,
        "Descricao" vARCHAR(60) NOT NULL,
        "Valor" numeric NOT NULL,
        "TipoProduto" text NOT NULL,
        "Ativo" boolean NOT NULL,
        CONSTRAINT "PK_Produtos" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220926230651_PrimeiraMigracao') THEN
    CREATE TABLE "Pedidos" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "ClienteId" integer NOT NULL,
        "IniciadoEm" timestamp without time zone NOT NULL DEFAULT (current_timestamp),
        "FinalizadoEm" timestamp without time zone NOT NULL,
        "TipoFrete" integer NOT NULL,
        "Status" text NOT NULL,
        "Observacao" VARCHAR(512) NULL,
        CONSTRAINT "PK_Pedidos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Pedidos_Clientes_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Clientes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220926230651_PrimeiraMigracao') THEN
    CREATE TABLE "PedidosItens" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "PedidoId" integer NOT NULL,
        "ProdutoId" integer NOT NULL,
        "Quantidade" integer NOT NULL DEFAULT 1,
        "Valor" numeric NOT NULL,
        "Desconto" numeric NOT NULL,
        CONSTRAINT "PK_PedidosItens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PedidosItens_Pedidos_PedidoId" FOREIGN KEY ("PedidoId") REFERENCES "Pedidos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PedidosItens_Produtos_ProdutoId" FOREIGN KEY ("ProdutoId") REFERENCES "Produtos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220926230651_PrimeiraMigracao') THEN
    CREATE INDEX idx_cliente_telefone ON "Clientes" ("Telefone");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220926230651_PrimeiraMigracao') THEN
    CREATE INDEX "IX_Pedidos_ClienteId" ON "Pedidos" ("ClienteId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220926230651_PrimeiraMigracao') THEN
    CREATE INDEX "IX_PedidosItens_PedidoId" ON "PedidosItens" ("PedidoId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220926230651_PrimeiraMigracao') THEN
    CREATE INDEX "IX_PedidosItens_ProdutoId" ON "PedidosItens" ("ProdutoId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220926230651_PrimeiraMigracao') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20220926230651_PrimeiraMigracao', '3.1.29');
    END IF;
END $$;
